id: I5CEA4800
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T19:57:39+00:00'
last_modified: '2022-06-08T06:54:20.183102+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8873
  title: པདྨ་འབྱུང་གནས་ཀྱི་རྣམ་ཐར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6E64:
      image_group_id: I1PD97307
      title: ''
      total_pages: 730
      order: 1
      base_file: 6E64.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
